added shit please dm me on discord @fifthwit for bounty ty
titaniumnetwork-dev/Oxide-Docs pull request #22
Opened 2024-08-29 05:40 UTC by FifthWit

did this for the bounty adds all the docs I thought were relevant and the kajigs, any that werent dead ig, probably a lot of them were but whatever discord is @fifthwit

2024-08-30 02:31 UTC, ProgrammerIn-wonderland commented
@TBNRAubrey review?

2024-08-30 02:33 UTC, r58Playz requested changes
Simply a copy paste of the readmes. Even the curltransport <-> twisp swap is still here. Don't merge

2024-08-30 02:35 UTC, FifthWit commented
> Simply a copy paste of the readmes. Even the curltransport <-> twisp swap is still here. Don't merge

thats the point genius, to centralize shit like kajigs lmao

2024-08-30 02:35 UTC, wearrrrr commented
Yeah, please keep in mind that MDX has more features than MD, and those are generally expected to be used here.

2024-08-30 02:36 UTC, r58Playz commented
> > Simply a copy paste of the readmes. Even the curltransport <-> twisp swap is still here. Don't merge
> 
> thats the point genius, to centralize shit like kajigs lmao

![image](https://github.com/user-attachments/assets/7618f733-5c21-4003-8fd0-46547d7e39c8)
This doesn't document anything.

2024-08-30 02:53 UTC, crazycrystals reviewed
its just copy pasted bruh you didnt convert to a "wiki" format and you copied kajigs and repos that did not need to be copied in the first place (rootesc kajig)

2024-08-30 02:53 UTC, crazycrystals commented on docs/kajigs/KIOSK_Exploit_DE-LICENSED_Original_.mdx
> +Note: The exploit should work consistently v76 or below but it's still possible to pull off on v85 or below, but only once (right after you powerwash).
did you even try to use the capabilities of MDX?
```
:::note
TEXT
:::
```

2024-08-30 02:53 UTC, crazycrystals commented on docs/kajigs/Omada_DNS.mdx
> +- This very commonly breaks locked mode quizes. To fix this, turn off omadadns and then restart your chromebook, go to chrome://policy, and then refresh policies. Wait for it to refresh, wait five mi
:::noteIssues
all that
:::
Also, actually link to other kajigs when you reference them. A wiki should allow you to go through it without having to actively search to find something it references.

2024-08-30 02:53 UTC, crazycrystals commented on docs/kajigs/Root_Escalation.mdx
this shouldnt be on the wiki. Its using the forum function. Also, you left the discord message link there

2024-08-30 02:53 UTC, crazycrystals commented on docs/kajigs/Shimboot.mdx
vk6 will KILL YOU for not giving him credit

2024-08-30 02:53 UTC, crazycrystals commented on docs/kajigs/Skiovox_Breakout.mdx
"\@akabutnice on discord"

oh shit and I realized your not doing double newlines so markdown is just not going to do newlines lmaoo

2024-08-30 02:53 UTC, crazycrystals commented on docs/kajigs/Skiovox_v125.mdx
tips as
:::noteTips
tips here
:::

2024-08-30 02:53 UTC, crazycrystals commented on docs/kajigs/Stealth_Lightspeed.mdx
:::note
noteshere
:::

2024-08-30 02:53 UTC, crazycrystals commented on docs/kajigs/UserPolicy_Bypass_.mdx
remove your DAMN discord links
anyways im done reviewing you get the point

2024-09-01 04:05 UTC, QuiteAFancyEmerald commented
I'm sorry going to have to deny this one; it doesn't even include all the TN repos so your uh pasting was not effective.

2024-09-01 04:05 UTC, closed without merging